note_keeping/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls'), name='notes'),
]

notes/urls.py
from django.urls import path
from . import views
import django.contrib.auth.views as auth_views


app_name='notes'

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='notes/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='notes/logged.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('settings/', views.settings, name='settings'),
    path('update/', views.update, name='update'),
    path('home/', views.home_page, name='home_page'),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Note(models.Model):
    title=models.CharField(max_length=45, null=False)
    description=models.TextField(null=False)
    author=models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

notes/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'notes/index.html')

def register(request):
    form=UserCreationForm()

    if request.method =='POST':
        form=UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Account created for {username}')
            return redirect('notes:login')
    context={
        'form':form,
    }
    return render(request, 'notes/register.html', context)


def settings(request):
    return render(request, 'notes/settings.html')

def loggedout(request):
    return render(request, 'notes/loggedout.html')

def update(request):
    return render(request, 'notes/update.html')

def home_page(request):
    return render(request, 'notes/home.html')

notes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static 'css/boostrap.min.css' %}">    <!-- CSS only -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">    
<title>Keep Notes</title>
</head>
<body>
    <header >
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <ul class="nav navbar-nav">
               
               {% if user.is_authenticated %}
               <li class="nav-item active">
                <a class="nav-link" href="{% url 'notes:home_page' %}">Keep Notes</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link add" href="#"> + Add Notes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link add" href="{% url 'notes:settings' %}">Settings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link add" href="{% url 'notes:logout' %}">Log Out</a>
            </li>
               {% else %}
               <li class="nav-item active">
                <a class="nav-link" href="{% url 'notes:index' %}">Keep Notes</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link add" href="{% url 'notes:register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link add" href="{% url 'notes:login' %}">Login</a>
            </li>
               {% endif %}
                   
            </ul>
        </nav>
    </header>
    {% block body%}
    {% endblock body%}
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

notes/templates/notes/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    

    
    <div class="container">
        <br>
        <h1>Recent Notes</h1>
        <div class="notes">
            
            {% for note in notes %}
            <div class="note">
                <h2 class="text-info">{{note.title}}</h2>
                <p>{{note.description}}</p>
                <div class="options">
                    <a href="/update/{{note.id}}/" class="btn btn-success">Update</a>
                    <a href="/delete/{{note.id}}/" class="btn btn-danger">Delete</a>
                </div>
            </div>
            {% endfor %}
                
        </div>
    </div>
    <div class="add-modal" id="add-modal">
        <div class="form">
            <form action="" method="post">
                {% csrf_token %}
                <h3>Add Note</h3>
               {{form |crispy}}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-danger close-btn" onclick="closeModal('add-modal')">Cancel</button>
                </div>
            </form>
        </div>
    </div>
    {% endblock body %}
   

notes/templates/notes/index.html
{% extends 'base.html' %}
{% block body%}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Keep Notes</h1>
            <p class="lead text-muted">This is a note keeping app built with Django</p>
            <p>
              <a href="{% url 'notes:register' %}" class="btn btn-primary my-2">Create an account</a>
              <a href="{% url 'notes:login' %}" class="btn btn-secondary my-2">Login</a>
            </p>
          </div>
        </div>
      </section>
{% endblock body%}

notes/templates/notes/loggedout.html
{% extends 'base.html' %}

{% block body %}

    
    
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">You have Logged Out</h1>
            <p class="lead text-muted">Thank you for spending quality time on the website</p>
            <p>
              <a href="{% url 'notes:login' %}" class="btn btn-secondary my-2">Login Again</a>
            </p>
          </div>
        </div>
      </section>
   
    
{% endblock body %}

notes/templates/notes/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    
    <div class="container">
        <div class="form">
            
            {% if messages %}
                
                {% for message in messages %}
                    <p class="alert alert-{{message.tags}}">{{message}}</p>
                {% endfor %}
                    
            {% endif %}
                
            <h3 class="text-primary">Login</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form |crispy}}
                <button type="submit" class="btn-info btn">Login</button>
            </form>
    </div>
    </div>
{% endblock body %}

notes/templates/notes/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}    
    <div class="container">
        <div class="form">
            <h3 class="text-primary">Sign Up</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" class="btn-info btn">Sign Up</button>
            </form>
    </div>
    </div>
{% endblock body %}

notes/templates/notes/settings.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}    
    <div class="container">
        <div class="form">
            <h3 class="text-primary">Account Settings</h3>
            {% if messages %}
                
            {% for message in messages %}
                <p class="alert alert-{{message.tags}}">{{message}}</p>
            {% endfor %}
                
        {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{form |crispy}}
                <button type="submit" class="btn-info btn">Save</button>
            </form>
    </div>
    </div>    
{% endblock body %}

notes/templates/notes/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}    
    <div class="container">
       <div class="form">
            <h3 class="text-primary">Update Note</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" class="btn-info btn">Update</button>
            </form>
       </div>
    </div>
{% endblock body %}